version: "3"

services:
  node-app:
    container_name: node-app
    image: node-deployment
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Explicitly tell SvelteKit where the app is being served.
      # This is almost always required when using the node-adapter and form actions.
      # It helps the node-adapter to correctly determine the url.
      # If this is not set, or set incorrectly, you might see the "Cross-site POST form submissions are forbidden" error when using form actions
      - ORIGIN=http://localhost:3000
    restart: always
    ports:
      - 3000:3000